---
- name: ensure all prequisites
  package:
    name: "{{item}}"
    state: present
  with_items:
    - python3.7
    - python3-pip
    - nginx
    - git
    - postgresql
    - python3-psycopg2 # for creating postgres users with ansible
    - python3-setuptools

- name: add byro user
  user:
    name: "{{byro_user}}"
    comment: byro system user
    state: present
    #      local: yes
    # disable password
    password: '!'
    home: /opt/byro
    
- name: add postgres user for byro
  postgresql_user:
    name: "{{byro_user}}"
    state: present
    login_unix_socket: /var/run/postgresql/
  become: true
  become_user: postgres

- name: create byro db
  postgresql_db:
    login_unix_socket: /var/run/postgresql/
    name: "{{byro_db_name}}"
    state: present
    owner: "{{byro_user}}"
  become: true
  become_user: postgres

- name: grant byro permissions on database
  postgresql_user:
    name: "{{byro_user}}"
    db: "{{byro_db_name}}"
    state: present
    login_unix_socket: /var/run/postgresql/
    priv: "ALL"
  become: true
  become_user: postgres

- name: install byro build dependcies
  package:
    name: "{{item}}"
    state: present
  with_items:
    - build-essential
    - python3-dev # i love inconplete documentation. rjsmin needs python.h
    - libssl-dev
    - gettext
    - libjpeg-dev # only part of the requiremts documented in the developer documentation, not the administrator docurmentation
    - libmagic-dev
    - python3-wheel # because the wheel installed with pip doesn't work

- name: create byro config directory
  file:
    path: /etc/byro
    owner: "{{byro_user}}"
    group: "{{byro_user}}"
    state: directory
    recurse: yes

- name: place byro config
  template:
    dest: /etc/byro/byro.cfg
    owner: byro
    group: byro
    mode: '0600'
    src: templates/byro.j2
  notify:
    - restart byro # wird nicht ausgeführt

- name: install python dependencies
  pip:
    executable: pip3
    name:
      - pip
      - setuptools
      - gunicorn
      - psycopg2-binary
    extra_args: --user
  become: true
  become_user: "{{byro_user}}"

- name: install byro
  pip:
    executable: pip3
    name:
      - git+https://github.com/MoritzFago/byro#subdirectory=src
    extra_args: --user
  notify:
    - restart byro
  become: true
  become_user: "{{byro_user}}"

- name: install byro plugins
  pip:
    executable: pip3
    name:
      - git+https://github.com/MoritzFago/byro-fints
      - git+https://github.com/MoritzFago/byro-gemeinnuetzigkeit
      - git+https://github.com/MoritzFago/byro-directdebit
      - git+https://github.com/MoritzFago/byro-toppoint
    extra_args: --user
  become: true
  become_user: "{{byro_user}}"

- name: create byro data directory
  file:
    path: /opt/byro/data/
    owner: "{{byro_user}}"
    group: "{{byro_user}}"
    state: directory
    recurse: yes

- name: create byro media directory
  file:
    path: /opt/byro/data/media
    owner: "{{byro_user}}"
    group: "{{byro_user}}"
    state: directory
    recurse: yes

- block:
  - name: make database migrations
    shell:
      cmd: python3 -m byro makemigrations
  - name: run database migrations
    shell:
      cmd: python3 -m byro migrate
  - name: create messages for byro # not documented https://stackoverflow.com/a/40649775
    shell:
      cmd: python3 -m byro makemessages
  - name: compile messages for byro
    shell:
      cmd: python3 -m byro compilemessages
  - name: collect static files
    shell:
      cmd: python3 -m byro collectstatic -c --noinput
  - name: compress files
    shell:
      cmd: python3 -m byro compress
  # create superuser by running: sudo -u byro python3 -m byro createsuperuser
  become: yes
  become_user: "{{byro_user}}"

- name: install systemd unit file
  template:
    src: templates/byro-web.service.j2
    dest: /etc/systemd/system/byro-web.service

- name: enable and start byro
  systemd:
    daemon_reload: yes
    name: byro-web
    enabled: yes

- name: place nginx config
  template:
    src: templates/byro.nginx.j2
    dest: /etc/nginx/sites-available/byro.conf
    # rm /etc/nginx/sites-enabled/default

- name: remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: enable webserver configuration
  file:
    path: /etc/nginx/sites-enabled/byro.conf
    src: ../sites-available/byro.conf
    state: link

